#!/bin/bash

clear
database="/root/usuarios.db"
echo $$ > /tmp/kids
while true; do
tput setaf 6 ; tput bold ; echo "                      SSH Monitor" ; tput sgr0
echo -e " \033[1;37m   Usuario                \033[1;36m|    \033[1;37mConectados/Limite    \033[0m"
echo -e "\033[1;36m ---------------------------------------------------\033[0m"
	 while read usline
	do
		user="$(echo $usline | cut -d' ' -f1)"
		s2ssh="$(echo $usline | cut -d' ' -f2)"
		if [ -z "$user" ] ; then
			echo "" > /dev/null
		else
			ps x | grep [[:space:]]$user[[:space:]] | grep -v grep | grep -v pts > /tmp/tmp8
			s1ssh="$(cat /tmp/tmp8 | wc -l)"
			echo -e "\033[1;37m    $(tput setaf 1 ; tput bold ; printf '%-41s%s' $user  ; tput setaf 5 ; tput bold ; printf         $s1ssh/$s2ssh ; tput sgr0) \033[0m"
			echo -e "\033[1;30m ---------------------------------------------------\033[0m"
		fi
	done < "$database"
	echo -e "\033[1;31mPressione CTRL + X para sair.\033[0m"
   tput setaf 6 ; tput bold ; read -n 1 -s -p "Pressione qualquer tecla para atualizar" ; echo "" ; echo "" ; tput sgr0
   clear
	done
exit 0