#!/bin/bash

clear
tput setaf 6 ; tput bold ; echo "" ; echo "Lista de usuários existente nesse servidor:" ; echo "" ; tput sgr0
tput setaf 1 ; tput bold ; awk -F : '$3 >= 500 { print $1 }' /etc/passwd | grep -v '^nobody' ; echo "" ; tput sgr0
tput setaf 5 ; tput bold ; read -p "Nome do usuário que deseja alterar a senha: " user ; tput sgr0
if [[ -z $user ]]
then
	echo -e "\033[1;31mErro! \033[1;37mVocê não digitou um nome de usuário ou digitou um nome inválido!\033[0m"
	echo
	echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"
				
	read resp
		if [ "$resp" == "s" ]; then
     		0012
		elif [ "$resp" == "n" ]; then
    		admm
		fi
else
	if [[ `grep -c /$user: /etc/passwd` -ne 0 ]]
	then
		tput setaf 5 ; tput bold; read -p "Digite uma nova senha para o usuário: " password ; tput sgr0
		sizepass=$(echo ${#password})
		if [[ $sizepass -lt 3 ]]
		then
			echo -e "\033[1;31mErro! \033[1;37mVocê digitou uma senha muito curta! Utilize no mínimo 3 caracteres.\033[0m"
			echo " "
				echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"

				read resp
				if [ "$resp" == "s" ]; then
					0012
				elif [ "$resp" == "n" ]; then
    				admm
				fi
		else
			ps x | grep $user | grep -v grep | grep -v pt > /tmp/rem
			if [[ `grep -c $user /tmp/rem` -eq 0 ]]
			then
				echo "$user:$password" | chpasswd
				echo
				echo -e "\033[1;36mA senha do usuário \033[1;31m$user \033[1;36mfoi alterada para \033[1;31m$password\033[0m"
				echo
				tput setaf 5 ; tput bold ; read -n 1 -s -p "Pressione qualquer tecla para finalizar..." ; echo "" ; echo "" ; tput sgr0
				admm
			else
				echo ""
				tput setaf 7 ; tput setab 4 ; tput bold ; echo "Desconectando usuário $user..." ; tput sgr0
				pkill -f $user
				echo "$user:$password" | chpasswd
				echo 
				echo -e "\033[1;36mA senha do usuário \033[1;31m$user foi alterada para \033[1;31m$password\033[0m"
				echo 
				tput setaf 5 ; tput bold ; read -n 1 -s -p "Pressione qualquer tecla para finalizar..." ; echo "" ; echo "" ; tput sgr0
				admm
			fi
		fi
	else
		tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "O usuário $user não existe!" ; echo "" ; tput sgr0
		echo " "
				echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"

				read resp
				if [ "$resp" == "s" ]; then
					0012
				elif [ "$resp" == "n" ]; then
    				admm
				fi
	fi
fi