#!/bin/bash

clear
database="/root/usuarios.db"
if [ ! -f "$database" ]
then
	echo -e "\033[1;31mFatal erro!  \033[1;37mArquivo $database não encontrado.\033[0m"
	echo
	tput setaf 6 ; tput bold ; read -n 1 -s -p "Pressione qualquer tecla para finalizar..." ; echo "" ; echo "" ; tput sgr0
else
   echo
	tput setaf 6 ; tput bold ; echo ""; echo "Limite de conexões simultâneas atuais dos usuários:" ; tput sgr0
	tput setaf 1 ; tput bold ; echo "" ; cat $database ; echo "" ; tput sgr0
	echo
	tput setaf 5 ; tput bold ; read -p "Nome do usuário que deseja alterar o limite: " usuario ; tput sgr0
	if [[ -z $usuario ]]
	then
		    echo "" 
			echo -e "\033[1;31mErro! \033[1;37mVocê digitou um nome de usuário vazio ou não existente na lista!\033[0m"
			echo " "
			echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"

			read resp
			if [ "$resp" == "s" ]; then
			0034
		elif [ "$resp" == "n" ]; then
    		admm
		fi
	else
		if [[ `grep -c "^$usuario " $database` -gt 0 ]]
		then
			   tput setaf 5 ; tput bold ; read -p "Digite o novo limite para $usuario: " sshnum ; tput sgr0
			if [[ -z $sshnum ]]
			then
				echo "" 
				echo -e "\033[1;31mErro! \033[1;37mVocê digitou um número inválido!\033[0m"
				echo " "
				echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"

				read resp
				if [ "$resp" == "s" ]; then
					0034
				elif [ "$resp" == "n" ]; then
    				admm
				fi
			else
				if (echo $sshnum | egrep [^0-9] &> /dev/null)
				then
					echo "" 
					echo -e "\033[1;31mErro! \033[1;37mUtilize apenas número.\033[0m"
					echo " "
					echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"

					read resp
					if [ "$resp" == "s" ]; then
						0034
					elif [ "$resp" == "n" ]; then
    					admm
				fi
				else
					if [[ $sshnum -lt 1 ]]
					then
						echo "" 
						echo -e "\033[1;31mErro! \033[1;37mVocê deve digitar um número maior que zero!\033[0m"
						echo " "
						echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"

						read resp
						if [ "$resp" == "s" ]; then
							0034
						elif [ "$resp" == "n" ]; then
    						admm
					fi
					else
						grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/a
						sleep 1
						mv /tmp/a /root/usuarios.db
						echo $usuario $sshnum >> /root/usuarios.db
						clear
						tput setaf 6 ; tput bold ; echo "" ; echo "Limite de conexões simultâneas para $usuario foi alterado com sucesso." ; tput sgr0
						echo
    					echo -e "\033[1;37mLista de usuários e limites atuais:\033[0m"
						tput setaf 1 ; tput bold ; echo "" ; cat $database ; echo "" ; tput sgr0
						tput setaf 5 ; tput bold ; read -n 1 -s -p "Pressione qualquer tecla para finalizar..." ; echo "" ; echo "" ; tput sgr0
 						admm
					fi
				fi
			fi			
		else
			    echo "" 
				echo -e "\033[1;31mErro! \033[1;37mUsuário $usuario não foi encontrado!\033[0m"
				echo " "
				echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"

				read resp
				if [ "$resp" == "s" ]; then
					0034
				elif [ "$resp" == "n" ]; then
    				admm
				fi
		fi
	fi
fi