#!/bin/bash

clear
echo -e "\033[1;36mMudar data de expiração\033[0m"
echo ""
tput setaf 7 ; tput bold ; echo "Lista de usuários e datas de expiração:" ; tput sgr0
echo ""
tput setaf 1 ; tput bold 
awk -F : '$3 >= 500 { print $1 }' /etc/passwd | grep -v '^nobody' | while read user
  do
	expire="$(chage -l $user | grep -E "Account expires" | cut -d ' ' -f3-)"
	if [[ $expire == "never" ]]
	then
		nunca="Nunca"
		printf '  %-30s%s\n' "$user" "Nunca"
	else
		databr="$(date -d "$expire" +"%Y%m%d")"
		hoje="$(date -d today +"%Y%m%d")"
		if [ $hoje -ge $databr ]
		then
			datanormal="$(date -d"$expire" '+%d/%m/%Y')"
			printf '  %-30s%s' "$user" "$datanormal" ; tput setaf 1 ; tput bold ; echo " (Expirado)" ; tput setaf 3
			echo "exp" > /tmp/exp
		else
			datanormal="$(date -d"$expire" '+%d/%m/%Y')"
			printf '  %-30s%s\n' "$user" "$datanormal"
		fi
	fi
  done
tput sgr0
echo ""
if [ -a /tmp/exp ]
then
	tput setaf 2 ; tput bold ; echo "Para remover todos os usuários expirados use o comando: expcleaner" ; echo "" ; tput sgr0
	rm /tmp/exp
fi
tput setaf 5 ; tput bold; read -p "Nome do usuário: " usuario ; tput sgr0
if [[ -z $usuario ]]
then
	echo ""
	echo -e "\033[1;31mErro! \033[1;37mVocê não digitou o nome do usuário!\033[0m"
	echo ""
				echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"

					read resp
						if [ "$resp" == "s" ]; then
							0035
						elif [ "$resp" == "n" ]; then
    						admm
						fi
else
	if [[ `grep -c /$usuario: /etc/passwd` -ne 0 ]]
	then
		tput setaf 5 ; tput bold ; read -p "Digite uma nova data de expiração (DIA/MÊS/ANO): " inputdate ; tput sgr0
		sysdate="$(echo "$inputdate" | awk -v FS=/ -v OFS=- '{print $3,$2,$1}')"
		if (date "+%Y-%m-%d" -d "$sysdate" > /dev/null  2>&1)
		then
			if [[ -z $inputdate ]]
			then
				echo ""
				tput setaf 7 ; tput bold ;	echo "Você digitou uma data inválida ou inexistente!" ; 
				echo -e "\033[1;31mDigite uma data válida no formato \033[1;31mDIA/MÊS/ANO,\033[1;31mpor exemplo: 21/04/2018.\033[0m"
				echo ""
				echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"

					read resp
						if [ "$resp" == "s" ]; then
							0035
						elif [ "$resp" == "n" ]; then
    						admm
						fi
			else
				if (echo $inputdate | egrep [^a-zA-Z] &> /dev/null)
				then
					today="$(date -d today +"%Y%m%d")"
					timemachine="$(date -d "$sysdate" +"%Y%m%d")"
					if [ $today -ge $timemachine ]
					then
						echo ""
						echo -e "Você digitou uma data passada ou o dia atual!\033[0m" 
						echo -e "\033[1;31mDigite uma data futura e válida no formato DIA/MÊS/ANO, por exemplo: \033[1;31m21/04/2020\033[0m"
						echo ""
						echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"

												read resp
												if [ "$resp" == "s" ]; then
													0035
												elif [ "$resp" == "n" ]; then
    												admm
											fi
					else
						chage -E $sysdate $usuario
						echo ""
						echo -e "\033[1;36mData de expiação do usuario \033[1;31m$usuario \033[1;36malterado com sucesso.\033[0m"
						tput setaf 7 ; tput bold ; echo "Nova data de expiração do usuário $usuario: $inputdate" ; tput sgr0
						echo ""
						tput setaf 5 ; tput bold ; read -n 1 -s -p "Pressione qualquer tecla para finalizar..." ; echo "" ; echo "" ; tput sgr0
						admm
					fi
				else
					echo ""
						echo -e "\033[1;31mErro! \033[1;37mVocê digitou uma data passada ou inexistente!\033[0m" 
						echo -e "\033[1;37mDigite uma data futura e válida no formato \033[1;37mDIA/MÊS/ANO.\033[0m" 
						echo -e "\033[1;37mPor exemplo: \033[1;31m21/04/2020\033[0m"
						echo ""
						echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"

												read resp
												if [ "$resp" == "s" ]; then
													0035
												elif [ "$resp" == "n" ]; then
    												admm
											fi
				fi
			fi
		else
			echo ""
						echo -e "\033[1;31mErro! \033[1;37mVocê digitou uma data passada ou inexistente!\033[0m" 
						echo -e "\033[1;37mDigite uma data futura e válida no formato \033[1;31mDIA/MÊS/ANO.\033[0m" 
						echo -e "\033[1;37mPor exemplo: \033[1;31m21/04/2020\033[0m"
						echo ""
						echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"

												read resp
												if [ "$resp" == "s" ]; then
													0035
												elif [ "$resp" == "n" ]; then
    												admm
											fi
		fi
	else
		echo " "
						echo -e "\033[1;31mO usuário $usuario não existe!\033[0m"
						echo ""
						echo -n -e "\033[1;31mDeseja tentar novamente(s/n):\033[0m"

												read resp
												if [ "$resp" == "s" ]; then
													0035
												elif [ "$resp" == "n" ]; then
    												admm
											fi
	fi
fi