#!/bin/bash

if [ $(id -u) -eq 0 ]
then
 clear
else
 if echo $(id) |grep sudo > /dev/null
 then
 clear
 echo -e "\033[1;31mErro! \033[1;37mNão é root e nem tem direitos root.\033[0m"
 echo -e "\033[1;36mParabéns seu usuario esta no grupo sudo.\033[0m"
 echo -e "\033[1;36mPara virar root execute \033[1;31msudo su\033[0m"
 exit
 else
 clear
 echo -e "\033[1;36mVocê nao esta como usuario root, nem com seus direitos (sudo)\npara virar root execute \033[1;31msu\033[0m \033[1;36me digite sua senha root\033[0m"
 exit
 fi
fi

function usuarios(){
clear
echo -e "\033[1;37m Qual tipo de usuário gostaria de criar?
\033[1;36m1|SSH
 \033[1;30m|Criar usuário com data de expiração em dias.
\033[1;36m2|Teste
 \033[1;30m|Criar usuário teste duração em segundos ou horas.
\033[1;36m3|OpenVPN
 \033[1;30m|Criar usuário OpenVPN
\033[1;36m4|Voltar
 \033[1;30m|Voltar ao menu anterior.\033[0m" 
read -p "Opção:" opcao

case $opcao in
 1)
  0011;;
 2) 
  0012;;
 3)
  0013;;
  4)
  admm;;
  *)
  id > /dev/null 2> /dev/null
esac
}

function redefinir(){
clear
echo -e "\033[1;37mO que deseja redefinir ?
\033[1;36m1|Nome
 \033[1;30m|Alterar nome de um usuário. 
\033[1;36m2|Senha
 \033[1;30m|Alterar senha de um usuário. 
\033[1;36m3|Deletar
 \033[1;30m|Deletar e desconectar todos os usuários.
\033[1;36m4|Limite
 \033[1;30m|Alterar limite de conexão de um usuário.
\033[1;36m5|Validade
 \033[1;30m|Alterar data de validade.
\033[1;36m6|Deletar todos
 \033[1;30m|Deletar todos os usuários.
\033[1;36m7|Voltar
 \033[1;30m|Voltar ao menu anterior.\033[0m" 
read -p "Opção:" opcao

case $opcao in
 1)
  0031;;
 2) 
  0032;;
 3)
  0033;;
 4)
  0034;;
 5)
   0035;;
 6)
   0036;;
 7)
   admm;;
  *)
  id > /dev/null 2> /dev/null
esac
}


clear
echo " "
echo -e "\033[1;36m       .....:::AdmManager, created by Mr.Devim:::.....\033[0m"
echo -e "\033[1;37mPara executar um comando escolha uma das opçoẽs abaixo.\033[0m"  

echo -e "\033[1;31mPara sair precione Ctrl + C\033
\033[1;36m1|Criar
 \033[1;30m|Gerenciamento de usuário SSH e OpenVPN.
\033[1;36m2|Rm Expirados
 \033[1;30m|Remover usuários expirados. 
\033[1;36m3|Redefinir
 \033[1;30m|Alterar senha, nome, data de validade, etc.
\033[1;36m4|Backup
 \033[1;30m|Opções de Backup dos usuários. 
\033[1;36m5|Monitorar
 \033[1;30m|Monitorar em tempo real as conexões.
\033[1;36m6|Host
 \033[1;30m|Adicionar Host a lista de permissão.
\033[1;36m7|Banner
 \033[1;30m|Visualizar, adicionar ou editar o banner SSH.
\033[1;36m8|Desinstalar
 \033[1;30m|Remover por completo o AdmManager.\033[0m"
read -p "Opção:" opcao

case $opcao in
 1)
  usuarios;;
 2) 
  0002;;
 3)
  redefinir;;
 4)
  0004;;
 5)
  0005;;
 6)
  0006;;
 7)
   0007;;
 8)
   0000;;
  *)
  id > /dev/null 2> /dev/null
esac
