#!/bin/bash

clear
    echo -e "\033[1;36mAdmManager, script gerenciador de servidor com diversas opções para lhe ajudar com o gerenciamento de usuários.\033[0m"
	echo
    tput setaf 5 ; tput bold ; read -n 1 -s -p "Pressione qualquer tecla para continuar com a instalação..." ; echo "" ; echo "" ; tput sgr0
echo
if [ -f "/root/usuarios.db" ]
then
	echo -e "\033[1;36mUma base de dados de usuários foi encontrada!\033[0m"
	echo
	echo -e "\033[1;35mO que deseja fazer?\033[0m" 
	echo -e "\033[1;36m1|Manter Base de Dados Atual\033[0m"
	echo -e "\033[1;30m |Preservando o limite de conexões simultâneas dos usuários\033[0m"
	echo -e "\033[1;36m2|Criar uma nova base de dados.\033[0m"
	echo -e "\033[1;30m |Criar base da dados novas e zerar a atual.\033[0m"
	tput setaf 5 ; tput bold ; read -p "Opção?: " -e -i 1 optiondb ; tput sgr0
else
	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > /root/usuarios.db
fi
if [[ "$optiondb" = '2' ]]; then
	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > /root/usuarios.db
fi
clear
tput setaf 6 ; tput bold ; echo "" ; echo "Iniciando preparativos..." ; echo "" ; tput sgr0
sleep 5s
echo
echo -e "\033[1;31mBaixando atualizações...\033[0m"
echo
apt-get update -y > /dev/null
apt-get install bc screen nano unzip dos2unix wget python-pip inxi -y > /dev/null
pip install speedtest-cli > /dev/null
echo -e "\033[1;37mInstalando atualizações...\033[0m"
sleep 10
echo
echo -e "\033[1;32mBaixando arquivos necessários...\033[0m"
sleep 8
echo
echo -e "\033[1;33mMovendo arquivos necessários...\033[0m"
sleep 9
echo
echo -e "\033[1;34mQuase no fim...\033[0m"
sleep 10
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/listar > /bin/listar
	chmod +x /bin/listar
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/admm > /bin/admm
	chmod +x /bin/admm
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0036 > /bin/0036
	chmod +x /bin/0036
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0035 > /bin/0035
	chmod +x /bin/0035
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0034 > /bin/0034
	chmod +x /bin/0034
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0033 > /bin/0033
	chmod +x /bin/0033
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0032 > /bin/0032
	chmod +x /bin/0032
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0031 > /bin/0031
	chmod +x /bin/0031
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0013 > /bin/0013
	chmod +x /bin/0013
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0012 > /bin/0012
	chmod +x /bin/0012
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0011 > /bin/0011
	chmod +x /bin/0011
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0007 > /bin/0007
	chmod +x /bin/0007
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0006 > /bin/0006
	chmod +x /bin/0006
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0005 > /bin/0005
	chmod +x /bin/0005
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0004 > /bin/0004
	chmod +x /bin/0004
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0002 > /bin/0002
	chmod +x /bin/0002
	wget -o /dev/null -O- https://raw.githubusercontent.com/Devimla/AdmManager/master/0000 > /bin/0000
	chmod +x /bin/0000
	clear
    echo -e "\033[1;36mConcluído, como usuário root ou usuário com permissões sudo execute:\033[0m"
	echo
	echo -e "\033[1;31madmm: \033[1;36mPara selecionar a opção desejada.\033[0m" 
	echo -e "\033[1;31mlistar: \033[1;36mPara ter uma lista dos atalhos disponíveis.\033[0m"
    echo
	tput setaf 5 ; tput bold ; read -n 1 -s -p "Pressione qualquer tecla para concluir..." ; echo "" ; echo "" ; tput sgr0
    admm